id: I4214FD1E
default_language: en
source: ''
initial_creation_type: tmx
imported: 2022-12-14 18:21:13.916025+00:00
last_modified: 2022-12-14 18:21:13.916031+00:00
source_metadata:
  creationtool: 84000-translation-memory
  creationtoolversion: 1.0.0.0
  datatype: PlainText
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: TEI
  creationdate: '2018-03-26T15:28:17.884Z'
  creationid: celso
  eft-text-id: UT22084-046-001
  xmlns-eft: http://read.84000.co/ns/1.0
  title: Toh_95-The_Play_in_Full-v1
bases:
  51AE:
    source_metadata: null
    order: 1
    base_file: 51AE.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
